version: '3'
services:
  db1:
    image: mysql:5.7
    networks:
    - lan1
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
  wp1:
    depends_on:
    - db1
    image: wordpress:${WORDPRESS_VERSION}
    user: '33:33'
    networks:
    - lan1
    ports:
    - 8001:80
    working_dir: /var/www/html
    volumes:
    - ./wp-content1/:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
  wpcli1:
    depends_on:
    - db1
    - wp1
    image: wordpress:cli
    user: '33:33'
    networks:
    - lan1
    volumes_from:
    - wp1
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
    command: " \n                    /bin/sh -c '\n                    sleep 60;\n\
      \                    wp core install --url=localhost:8001 --title=\"${BLOG_TITLE}\"\
      \ --admin_name=${WORDPRESS_ADMIN} --admin_password=${WORDPRESS_ADMIN_PSW} --admin_email=${WORDPRESS_MAIL}\n\
      \                    wp plugin install forminator --version=1.28.0 --activate\
      \ --allow-root\n                    wp theme install hello-elementor --version=2.9.0\
      \ --activate --allow-root\n                    '\n                    "
networks:
  lan1:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
