version: '3'
services:
  rev:
    image: nginx
    ports:
    - 443:443
    volumes:
    - ./proxy/log:/var/log/nginx/
    - ./proxy/ssl:/etc/nginx/ssl
    - ./proxy/conf:/etc/nginx/conf.d
    networks:
    - lan1
    - lan2
  db1:
    image: mysql:5.7
    networks:
    - lan1
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
  wp1:
    depends_on:
    - db1
    image: wordpress:${WORDPRESS_VERSION}
    networks:
      lan1:
        ipv4_address: 10.0.1.5
    ports:
    - 8001:80
    working_dir: /var/www/html/hp1
    volumes:
    - ./hp1/wp-content1/:/var/www/html/hp1/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
  wpcli1:
    depends_on:
    - db1
    - wp1
    image: wordpress:cli
    user: '33:33'
    networks:
    - lan1
    volumes_from:
    - wp1
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
    command: " \n                    /bin/sh -c '\n                    sleep 60;\n\
      \                    wp core install --path=/var/www/html/hp1 --url=172.28.49.205:8001/hp1\
      \ --title=\"Unito Informatica\" --admin_name=${WORDPRESS_ADMIN} --admin_password=${WORDPRESS_ADMIN_PSW}\
      \ --admin_email=${WORDPRESS_MAIL}\n                    wp search-replace --path=/var/www/html/hp1\
      \ 'http://172.28.49.205:8001/hp1' 'http://172.28.49.205/hp1'\n             \
      \       wp plugin install --path=/var/www/html/hp1 forminator --version=1.28.0\
      \ --activate --allow-root\n\n                    wp theme install --path=/var/www/html/hp1\
      \ hello-elementor --version=2.9.0 --activate --allow-root\n\n              \
      \      '\n                    "
  db2:
    image: mysql:5.7
    networks:
    - lan2
    ports:
    - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
  wp2:
    depends_on:
    - db2
    image: wordpress:${WORDPRESS_VERSION}
    networks:
      lan2:
        ipv4_address: 10.0.2.5
    ports:
    - 8002:80
    working_dir: /var/www/html/hp2
    volumes:
    - ./hp2/wp-content2/:/var/www/html/hp2/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
  wpcli2:
    depends_on:
    - db2
    - wp2
    image: wordpress:cli
    user: '33:33'
    networks:
    - lan2
    volumes_from:
    - wp2
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
    command: " \n                    /bin/sh -c '\n                    sleep 60;\n\
      \                    wp core install --path=/var/www/html/hp2 --url=172.28.49.205:8002/hp2\
      \ --title=\"Unito Medicina\" --admin_name=${WORDPRESS_ADMIN} --admin_password=${WORDPRESS_ADMIN_PSW}\
      \ --admin_email=${WORDPRESS_MAIL}\n                    wp search-replace --path=/var/www/html/hp2\
      \ 'http://172.28.49.205:8002/hp2' 'http://172.28.49.205/hp2'\n             \
      \       wp plugin install --path=/var/www/html/hp2 social-share-buttons-lite\
      \ --version=1.0.9 --activate --allow-root\n\n                    wp theme install\
      \ --path=/var/www/html/hp2 oceanwp --version=3.5.3 --activate --allow-root\n\
      \n                    '\n                    "
networks:
  lan1:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
  lan2:
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24

