version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
    - 3306:3306
    #volumes:
    #  - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}

  wordpress:
    depends_on:
      - db
    image: wordpress:${WORDPRESS_VERSION}
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
     - ./wp-content/:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
  
  wpcli:
    depends_on:
     - db
     - wordpress
    image: wordpress:cli
    volumes_from:
     - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
    command: >
      /bin/sh -c '
      sleep 30;
      wp core install --url=localhost:8000 --title="${BLOG_TITLE}" --admin_name=${WORDPRESS_ADMIN} --admin_password=${WORDPRESS_ADMIN_PSW} --admin_email=${WORDPRESS_MAIL}
      '
    #command: --info
#volumes:
#    db_data: {}
