version: '3'
services:
  rev:
    image: nginx
    ports:
    - 443:443
    volumes:
    - ./proxy/log:/var/log/nginx/
    - ./proxy/ssl:/etc/nginx/ssl
    - ./proxy/conf:/etc/nginx/conf.d
    networks:
      lan1:
        ipv4_address: 10.0.1.10
      lan2:
        ipv4_address: 10.0.2.10
  db1:
    image: mysql:5.7
    networks:
    - lan1
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
  wp1:
    depends_on:
    - db1
    image: wordpress:latest
    networks:
      lan1:
        ipv4_address: 10.0.1.5
    ports:
    - 8001:80
    working_dir: /var/www/html/hp1
    volumes:
    - ./hp1/wp-content1/:/var/www/html/hp1/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: wordpress
  wpcli1:
    depends_on:
    - db1
    - wp1
    image: wordpress:cli
    user: '33:33'
    networks:
    - lan1
    volumes_from:
    - wp1
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: wordpress
    command: " \n                    /bin/sh -c '\n                    sleep 60;\n\
      \                    wp core install --path=/var/www/html/hp1 --url=172.28.60.43:8001/hp1\
      \ --title=\"Sito di Irene\" --admin_name=wp-admin --admin_password=MyStr0ngP4ss\
      \ --admin_email=unito.admin@mail.com\n                    wp search-replace\
      \ --path=/var/www/html/hp1 'http://172.28.60.43:8001/hp1' 'http://172.28.60.43/hp1'\n\
      \                    wp plugin install --path=/var/www/html/hp1 forminator --version=1.28.0\
      \ --activate --allow-root\n\n                    wp theme install --path=/var/www/html/hp1\
      \ hello-elementor --version=2.9.0 --activate --allow-root\n\n              \
      \      '\n                    "
  db2:
    image: mysql:5.7
    networks:
    - lan2
    ports:
    - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
  wp2:
    depends_on:
    - db2
    image: wordpress:latest
    networks:
      lan2:
        ipv4_address: 10.0.2.5
    ports:
    - 8002:80
    working_dir: /var/www/html/hp2
    volumes:
    - ./hp2/wp-content2/:/var/www/html/hp2/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: wordpress
  wpcli2:
    depends_on:
    - db2
    - wp2
    image: wordpress:cli
    user: '33:33'
    networks:
    - lan2
    volumes_from:
    - wp2
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: wordpress
    command: " \n                    /bin/sh -c '\n                    sleep 60;\n\
      \                    wp core install --path=/var/www/html/hp2 --url=172.28.60.43:8002/hp2\
      \ --title=\"Sito di Zaira\" --admin_name=wp-admin --admin_password=MyStr0ngP4ss\
      \ --admin_email=unito.admin@mail.com\n                    wp search-replace\
      \ --path=/var/www/html/hp2 'http://172.28.60.43:8002/hp2' 'http://172.28.60.43/hp2'\n\
      \                    wp plugin install --path=/var/www/html/hp2 social-share-buttons-lite\
      \ --version=1.0.9 --activate --allow-root\n\n                    wp theme install\
      \ --path=/var/www/html/hp2 oceanwp --version=3.5.3 --activate --allow-root\n\
      \n                    '\n                    "
networks:
  lan1:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
  lan2:
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
